### ISSUE TITLE
Should the package itself contain data bases?

### ISSUE THREAD

**Issue by nickhaf** [beckerbenj/eatRecode#11]
@beckerbenj : This could add to usability, because users could simply specify which data base they want to use, for example `lookup = "language"`. 

One major issue would be the question of how to update the databases. Maybe we could establish some workflow using Pull requests that have to be reviewed, before the update goes live? This would also be nice because the changes would be checked again by a second person.

**Comment by beckerbenj** [comment]
Difficult to implement due to data disclosure concerns; closed for now.
