### ISSUE TITLE
Automatic updating of data base

### ISSUE THREAD

**Issue by beckerbenj** [beckerbenj/eatRecode#2]

**Comment by beckerbenj** [comment]
Question @enkeflor and @liebelta:
How should `updateRecodeDB()` deal with recodes that contradict the information in the data base? For instance, if a false recoding scheme was corrected or had to be updated?

Should `updateRecodeDB()` update these cases automatically? If so, should it report those updates via a message? Should this be open for choice via an argument `override` argument?

**Comment by enkeflor** [comment]
A report message of those instances is useful. Preferred would be an `override` argument for choosing which instance should be overwritten.
