### ISSUE TITLE
Which checks should be done in `extractManualRecode`?

### ISSUE THREAD

**Issue by nickhaf** [beckerbenj/eatRecode#20]
@beckerbenj :

Problem:  User can choose a column name for the new column in `useRecodeList()`. `extractManualRecode()` makes the assumption, the column with the recoded values is named `newValues`.
Should `extractManualRecode()` take an argument for the name of the new column or should `useRecodeList()` always force the column names `newValue`?

**Comment by beckerbenj** [comment]
I think I would prefer to change this in `useRecodeList()` and have the package wide assumption that the columns of the `recodeList` are named consistently `oldValues` and `newValues`.

Could you implement such a change?

**Comment by nickhaf** [comment]
Yes, I agree. Will implement
