### ISSUE TITLE
rename `recodedList` in `extractManualRecode()` to `recodedDf`

### ISSUE THREAD

**Issue by nickhaf** [beckerbenj/eatRecode#22]
@beckerbenj :
I'd like to seperate it more from a `recodeList`, as the argument in this function is actually the recoded data frame put into `useRecodeList()`. The current name suggests that it is some kind of recodeList, even though it is not, as it still contains `NAs`, and could also contain additional columns.

**Comment by beckerbenj** [comment]
Agree, sounds like a good idea!
