### ISSUE TITLE
Improve error messages

### ISSUE THREAD

**Issue by nickhaf** [beckerbenj/eatRecode#39]
The `checkmate` assertions are not very informative for end users. 

Example: `updateRecodeDB()` throws an error, if columns in the database are not named correctly. However, the error message is not too easy to understand for end users. @grewered could you look into it, and let `checkmate` throw a clearer error message in that case, something like "please make sure the columns in your database are named `oldValues` and `newValues` (in each sheet if you have an excel file)" or something similar?

**Comment by grewered** [comment]
I can have a look at that. 
It might work with assert_subset(), but I'm not sure about custom error messages. But I think that was possible.
