### ISSUE TITLE
Add pkgdown

### ISSUE THREAD

**Issue by beckerbenj** [beckerbenj/eatRecode#7]

**Comment by nickhaf** [comment]
@beckerbenj : I get a 404 error, which could indicate authentification problems (https://docs.github.com/en/rest/overview/troubleshooting?apiVersion=2022-11-28) when using ` usethis::use_pkgdown_github_pages()`. Could you please try to run this command for setting up pkgdown? Or do you have an idea how to deal with this error message (A quick google search didn't turn up anything): 

```
✔ Writing '_pkgdown.yml'
• Modify '_pkgdown.yml'
✔ Activating GitHub Pages for 'beckerbenj/eatRecode'
Error in `gh::gh()`:
! GitHub API error (404): Not Found
✖ URL not found: <https://api.github.com/repos/beckerbenj/eatRecode/pages>
ℹ Read more at <https://docs.github.com/rest/pages/pages#create-a-apiname-pages-site>
Run `rlang::last_trace()` to see where the error occurred.
```

**Comment by nickhaf** [comment]
I've now tried it with my own fork, which worked, so I suppose there might be some problem with the writing permissions?

**Comment by beckerbenj** [comment]
Seemed to be indeed a permission issue 🤷
